version: '2'

services:
  s2t:
    image: mkaichen/s2t:latest
    environment:
      - DB_HOST=centralmongodb
      - UAS_HOST=uniaudio
      - UAS_PORT=8080
    ports:
      - '8080:8080'
    depends_on: 
      - centralmongodb

  test_s2t:
    image: mkaichen/s2t:latest
    build: .
    command: [ "npm", "test" ]

  centralmongodb:
    image: mongo:latest
    volumes: 
      - /data/database
    restart: always
